version: '2'
services:
    yiyi-cassandra:
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/YIYI/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    yiyi-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=yiyi-cassandra
    yiyi-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: yiyi-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
